
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 19;
  public static final int NUMERO = 42;
  public static final int BVAR = 41;
  public static final int AC = 32;
  public static final int CHAR = 48;
  public static final int POR = 26;
  public static final int GE = 13;
  public static final int INT = 46;
  public static final int IMPLICA = 17;
  public static final int FOR = 6;
  public static final int CP = 31;
  public static final int NOT = 14;
  public static final int AND = 15;
  public static final int IGUAL = 29;
  public static final int LT = 10;
  public static final int CL = 35;
  public static final int LETRA = 45;
  public static final int OR = 16;
  public static final int VERDAD = 52;
  public static final int DIV = 27;
  public static final int CC = 33;
  public static final int IF = 2;
  public static final int LE = 11;
  public static final int BOOLEAN = 51;
  public static final int EOF = 0;
  public static final int PALABRA = 50;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int DIMPLICA = 18;
  public static final int CASTI = 54;
  public static final int MENOS = 25;
  public static final int EXISTS = 20;
  public static final int CASTB = 53;
  public static final int EQ = 8;
  public static final int FROM = 21;
  public static final int REAL = 43;
  public static final int NEG = 28;
  public static final int ELSE = 3;
  public static final int PUNTO = 38;
  public static final int TO = 22;
  public static final int WHILE = 5;
  public static final int FLOAT = 47;
  public static final int NE = 9;
  public static final int STRING = 49;
  public static final int UNICODE = 44;
  public static final int AP = 30;
  public static final int GT = 12;
  public static final int VAR = 40;
  public static final int LENGTH = 39;
  public static final int PRINT = 7;
  public static final int DO = 4;
  public static final int PYC = 36;
  public static final int STEP = 23;
  public static final int AL = 34;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "PRINT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "NOT",
  "AND",
  "OR",
  "IMPLICA",
  "DIMPLICA",
  "FORALL",
  "EXISTS",
  "FROM",
  "TO",
  "STEP",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "NEG",
  "IGUAL",
  "AP",
  "CP",
  "AC",
  "CC",
  "AL",
  "CL",
  "PYC",
  "COMA",
  "PUNTO",
  "LENGTH",
  "VAR",
  "BVAR",
  "NUMERO",
  "REAL",
  "UNICODE",
  "LETRA",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "PALABRA",
  "BOOLEAN",
  "VERDAD",
  "CASTB",
  "CASTI"
  };
}

